all: 
	g++ -I/usr/local/include src/BGPNcurses.cpp src/ncurses/ncursesFunctions.cpp src/ncurses/OutageData.cpp -o Display /usr/local/lib/libbgpstream.so /usr/lib/x86_64-linux-gnu/libncurses.so  -lboost_system -lboost_thread

