include(FindPackageHandleStandardArgs)

find_path(LIBBGPSTREAM_INCLUDE_DIR bgpstream.h)
find_library(LIBBGPSTREAM_LIBRARY NAMES bgpstream)

find_package_handle_standard_args(LibBGPStream DEFAULT_MSG
  LIBBGPSTREAM_LIBRARY LIBBGPSTREAM_INCLUDE_DIR)

mark_as_advanced(LIBBGPSTREAM_INCLUDE_DIR LIBBGPSTREAM_LIBRARY)

set(LIBBGPSTREAM_LIBRARIES ${LIBBGPSTREAM_LIBRARY})
set(LIBBGPSTREAM_INCLUDE_DIRS ${LIBBGPSTREAM_INCLUDE_DIR})

